version: 4.4.{build}-appveyor
image: Visual Studio 2015
configuration:
- Debug
- Release
build:
  parallel: true
  verbosity: minimal
build_script:
  - cmd: .\build.cmd mode=%CONFIGURATION%
after_build:
  - cmd: .paket\paket.exe pack output artifacts symbols buildconfig %CONFIGURATION% -v
artifacts:
  - path: '**\*QuickFont*.nupkg'
